//
// Created by Noa Storm on 25/09/2024.
//

#ifndef GREENHOUSE_CONTROLLER_CONFIG_H
#define GREENHOUSE_CONTROLLER_CONFIG_H

#define BTN0_PIN 9
#define BTN1_PIN 8
#define BTN2_PIN 7
#define ROT_SW_PIN 12

#define ROT_A_PIN 10
#define ROT_B_PIN 11
#define ROT_SW_PIN 12

#define UART0_TX_PIN 0
#define UART0_RX_PIN 1

#define UART1_TX_PIN 4
#define UART1_RX_PIN 5
#define UART1_BAUD_RATE 9600
#define UART1_STOP_BITS 2

#define CO2_DISSIPATOR_PIN 27

#define TASK_BUTTON_PRIORITY (tskIDLE_PRIORITY + 1)
#define TASK_ROTARY_PRIORITY (tskIDLE_PRIORITY + 1)
#define TASK_EEPROM_PRIORITY (tskIDLE_PRIORITY + 2)
#define TASK_CONTROLLER_PRIORITY (tskIDLE_PRIORITY + 3)
#define TASK_GAS_PRIORITY (tskIDLE_PRIORITY + 4)
#define TASK_CO2_PROBE_PRIORITY (tskIDLE_PRIORITY + 2)

#define EEPROM_DEVICE_ADDRESS 0x50
#define EEPROM_ADDRESS_BITS 15
#define EEPROM_ADDRESS_SIZE ((EEPROM_ADDRESS_BITS+7)/8)
#define EEPROM_PAGE_SIZE 64
#define EEPROM_FLUSH_TIME_MS 10

#define NETWORK_SSID_MAX_LENGTH 24
#define NETWORK_PASSWORD_MAX_LENGTH 32
#define NETWORK_SSID_DEFAULT ""
#define NETWORK_PASSWORD_DEFAULT ""
#define PPM_TARGET_DEFAULT 400

#endif //GREENHOUSE_CONTROLLER_CONFIG_H
