//
// Created by Noa Storm on 25/09/2024.
//

#ifndef GREENHOUSE_CONTROLLER_CONFIG_H
#define GREENHOUSE_CONTROLLER_CONFIG_H

#define BTN0_PIN 9
#define BTN1_PIN 8
#define BTN2_PIN 7
#define ROT_SW_PIN 12

#define ROT_A_PIN 10
#define ROT_B_PIN 11
#define ROT_SW_PIN 12

#define TASK_BUTTON_PRIORITY (tskIDLE_PRIORITY + 1)
#define TASK_ROTARY_PRIORITY (tskIDLE_PRIORITY + 1)
#define TASK_EEPROM_PRIORITY (tskIDLE_PRIORITY + 1)

#endif //GREENHOUSE_CONTROLLER_CONFIG_H
